# bash completion support for lifli
# DO NOT EDIT.
# This script is autogenerated by fire/completion.py.

_complete-lifli()
{
  local cur prev opts lastcommand
  COMPREPLY=()
  prev="${COMP_WORDS[COMP_CWORD-1]}"
  cur="${COMP_WORDS[COMP_CWORD]}"
  lastcommand=$(get_lastcommand)

  opts=""
  GLOBAL_OPTIONS=""


  case "${lastcommand}" in
  
    distribution)
      
      if is_prev_global; then
        opts="${GLOBAL_OPTIONS}"
      else
        opts="--data-folder ${GLOBAL_OPTIONS}"
      fi
      opts=$(filter_options $opts)
    ;;

    fix)
      
      if is_prev_global; then
        opts="${GLOBAL_OPTIONS}"
      else
        opts="--data-folder ${GLOBAL_OPTIONS}"
      fi
      opts=$(filter_options $opts)
    ;;

    predict)
      
      if is_prev_global; then
        opts="${GLOBAL_OPTIONS}"
      else
        opts="--image-path ${GLOBAL_OPTIONS}"
      fi
      opts=$(filter_options $opts)
    ;;

    evaluate-folder)
      
      if is_prev_global; then
        opts="${GLOBAL_OPTIONS}"
      else
        opts="--data-folder ${GLOBAL_OPTIONS}"
      fi
      opts=$(filter_options $opts)
    ;;

    transformation)
      
      if is_prev_global; then
        opts="${GLOBAL_OPTIONS}"
      else
        opts="--dest --paf ${GLOBAL_OPTIONS}"
      fi
      opts=$(filter_options $opts)
    ;;

    train)
      
      if is_prev_global; then
        opts="${GLOBAL_OPTIONS}"
      else
        opts="--data-folder --device --epochs ${GLOBAL_OPTIONS}"
      fi
      opts=$(filter_options $opts)
    ;;

    lifli)
      
      opts="augmentation distribution evaluate-folder fix predict train transformation ${GLOBAL_OPTIONS}" 
      opts=$(filter_options $opts)
    ;;
  esac

  COMPREPLY=( $(compgen -W "${opts}" -- ${cur}) )
  return 0
}

get_lastcommand()
{
  local lastcommand i

  lastcommand=
  for ((i=0; i < ${#COMP_WORDS[@]}; ++i)); do
    if [[ ${COMP_WORDS[i]} != -* ]] && [[ -n ${COMP_WORDS[i]} ]] && [[
      ${COMP_WORDS[i]} != $cur ]]; then
      lastcommand=${COMP_WORDS[i]}
    fi
  done

  echo $lastcommand
}

filter_options()
{
  local opts
  opts=""
  for opt in "$@"
  do
    if ! option_already_entered $opt; then
      opts="$opts $opt"
    fi
  done

  echo $opts
}

option_already_entered()
{
  local opt
  for opt in COMP_WORDS
  do
    if [ $1 == $opt ]; then
      return 0
    fi
  done
  return 1
}

is_prev_global()
{
  local opt
  for opt in $GLOBAL_OPTIONS
  do
    if [ $opt == $prev ]; then
      return 0
    fi
  done
  return 1
}

complete -F _complete-lifli lifli

